name: Docker Image CI

on:
  pull_request:
    branches: ["main"]
  #Allow mannually trigger
  workflow_dispatch:

  jobs:
    build:
      runs-on: macOS-Ventura
      steps:
        - uses: actions/checkout@v3
        - name: Build the Codespoaces container image
          run: docker build . --file .devcontainer/Dockerfile
